CREATE DATABASE SI_GESTAO_ACADEMICO;

--TABELA ALUNOS
CREATE TABLE ALUNOS (
	ID SERIAL PRIMARY KEY,
	IDCURSO INTEGER,
	RA VARCHAR NOT NULL,
	NOME VARCHAR NOT NULL,
	DATACADASTRO DATE NOT NULL,
	EMAIL VARCHAR,
	TELEFONE VARCHAR,
	ENDERECO VARCHAR,
	INICIOCURSO DATE,
	CONCLUSAOCURSO DATE,
	STATUS VARCHAR(1) NOT NULL
);

--TABELA CURSOS
CREATE TABLE CURSOS (
	ID SERIAL PRIMARY KEY,
	IDPROFESSOR INTEGER,
	CODIGO VARCHAR NOT NULL,
	NOME VARCHAR NOT NULL,
	DESCRICAO VARCHAR NOT NULL,
	CARGAHORARIA INT NOT NULL,
	MODALIDADE VARCHAR,
	NIVEL VARCHAR
);

--TABELA PROFESSORES
CREATE TABLE PROFESSORES(
	ID SERIAL PRIMARY KEY,
	IDDEPARTAMENTO INTEGER,
	CODIGO VARCHAR NOT NULL,
	NOME VARCHAR NOT NULL,
	DATANASCIMENTO DATE,
	EMAIL VARCHAR,
	DATACADASTRO DATE,
	COORDENADOR BOOLEAN DEFAULT FALSE,
	DESLIGAMENTO BOOLEAN,
	DATADESLIGAMENTO DATE
);

--TABELA DEPARTAMENTO
CREATE TABLE DEPARTAMENTOS (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	CODIGO VARCHAR NOT NULL
);

--- CRIANDO AS NOSSAS CHAVES ESTRANGEIRAS
--	FOREIGN KEY
ALTER TABLE ALUNOS
ADD CONSTRAINT FK_ALUNOS_CURSOS
FOREIGN KEY (IDCURSO) REFERENCES CURSOS(ID);

ALTER TABLE CURSOS
ADD CONSTRAINT FK_CURSOS_PROFESSORES
FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSORES(ID);

ALTER TABLE PROFESSORES
ADD CONSTRAINT FK_PROFESSORES_DEPARTAMENTOS
FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID);

--VERIFICANDO AS CONSTRAINTS DAS TABELAS CRIADAS
SELECT 
	CONNAME, 
	PG_GET_CONSTRAINTDEF(C.OID) AS CONSTRAINT_DEF,
	CONRELID
FROM 
	PG_CONSTRAINT C
WHERE 
	CONRELID IN ('alunos'::regclass,
				   'cursos'::regclass,
				   'professores'::regclass,
				   'departamentos'::regclass
				  );


--VIOLANDO FOREIGN KEY PARA TESTAR INTEGRIDADE REFERENCIAL
INSERT INTO ALUNOS 
	(IDCURSO, RA, NOME, DATACADASTRO, EMAIL, TELEFONE, ENDERECO, INICIOCURSO, CONCLUSAOCURSO, STATUS) 
VALUES
  -- Alunos do curso 1
  (1, '000001', 'Lucas Souza', '2023-09-02', 'lucas.souza@univale.com.br', '(11) 99999-1111', 'Rua das Flores, 123, São Paulo', '2023-09-02', NULL, 'C')
  








